# Generated by Django 3.2 on 2023-08-10 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntntsNo', models.IntegerField()),
                ('cntntsSj', models.CharField(max_length=300, null=True)),
                ('rtnFileUrl', models.URLField(null=True)),
                ('rtnThumbFileUrl', models.URLField(null=True)),
                ('growthAra', models.IntegerField(blank=True, null=True)),
                ('growthHg', models.IntegerField(blank=True, null=True)),
                ('grwhTp', models.CharField(blank=True, max_length=100, null=True)),
                ('minTp', models.IntegerField(blank=True, null=True)),
                ('maxTp', models.IntegerField(blank=True, null=True)),
                ('grwtve', models.IntegerField(blank=True, null=True)),
                ('hd', models.CharField(blank=True, max_length=100, null=True)),
                ('minHd', models.IntegerField(blank=True, null=True)),
                ('maxHd', models.IntegerField(blank=True, null=True)),
                ('ignSeasonCode', models.CharField(max_length=4, null=True)),
                ('ignSeason', models.CharField(blank=True, max_length=100, null=True)),
                ('lighttdemanddo', models.CharField(blank=True, max_length=300, null=True)),
                ('minLt', models.IntegerField(blank=True, null=True)),
                ('maxLt', models.IntegerField(blank=True, null=True)),
                ('managedemanddo', models.IntegerField(blank=True, null=True)),
                ('minPstPlc', models.IntegerField(blank=True, null=True)),
                ('maxPstPlc', models.IntegerField(blank=True, null=True)),
                ('toxcty', models.IntegerField(blank=True, null=True)),
                ('watercycleSprng', models.IntegerField(blank=True, null=True)),
                ('watercycleSummer', models.IntegerField(blank=True, null=True)),
                ('watercycleAutum', models.IntegerField(blank=True, null=True)),
                ('watercycleWinter', models.IntegerField(blank=True, null=True)),
                ('minWinterTp', models.IntegerField(blank=True, null=True)),
                ('maxWinterTp', models.IntegerField(blank=True, null=True)),
                ('winterLwetTp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='plant_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입양 날짜'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='watering_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='물 준 날짜'),
        ),
        migrations.AlterField(
            model_name='character',
            name='angry_emo',
            field=models.ImageField(blank=True, null=True, upload_to='character/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='basic_emo',
            field=models.ImageField(blank=True, null=True, upload_to='character/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='happy_emo',
            field=models.ImageField(blank=True, null=True, upload_to='character/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sad_emo',
            field=models.ImageField(blank=True, null=True, upload_to='character/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('reference_photo', models.ImageField(blank=True, upload_to='request/%Y/%m/%d/')),
                ('is_confirm', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(verbose_name='응답')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_id', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
