# Generated by Django 3.2 on 2023-09-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_scheduledplantdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='plant_id',
            field=models.ForeignKey(db_column='plant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='plant.plantinfo'),
        ),
    ]
