# Generated by Django 3.2 on 2023-09-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_scheduledplantdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='plant_id',
            field=models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='plant.plantinfo'),
        ),
    ]
