# Generated by Django 3.2 on 2023-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_bookmark_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
