# Generated by Django 3.2 on 2023-09-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_alter_plantinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plantinfo'),
        ),
    ]
