# Generated by Django 3.2 on 2023-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입양 날짜'),
        ),
        migrations.AddField(
            model_name='partner',
            name='watering_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='물 준 날짜'),
        ),
    ]
