# Generated by Django 3.2 on 2023-06-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20230524_1514'),
        ('plant', '0008_chat'),
    ]

    operations = [
    ]
