# Generated by Django 3.2 on 2023-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20230913_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledplantdata',
            name='humid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledplantdata',
            name='light',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledplantdata',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
