# Generated by Django 3.2 on 2023-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_merge_0008_auto_20230524_1514_0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='plant_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
