# Generated by Django 3.2 on 2023-11-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20231030_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantinfo',
            old_name='watercycleAutum',
            new_name='watercycleAutumn',
        ),
    ]
