# Generated by Django 3.2 on 2023-05-08 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230508_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
